CREATE TABLE ARCHITECTURE (
  ID          INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  NAME        VARCHAR(255)    NOT NULL,
  DESCRIPTION CLOB(1073741823),
  USECASE     CLOB(1073741823),
  PREVIEW     BLOB
);
CREATE TABLE LAYER (
  ID          INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  ARCH_ID     INT             NOT NULL,
  NAME        VARCHAR(255)    NOT NULL,
  DESCRIPTION CLOB(1073741823),
  USECASE     CLOB(1073741823)
);

CREATE TABLE MODULE (
  ID          INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  LAY_ID      INT             NOT NULL,
  NAME        VARCHAR(255)    NOT NULL,
  DESCRIPTION CLOB(1073741823)
);

CREATE TABLE PATERNS (
  ID          INT PRIMARY KEY  NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  MOD_ID      INT              NOT NULL,
  NAME        VARCHAR(255)     NOT NULL,
  VALUE       CLOB(1073741823) NOT NULL,
  DESCRIPTION CLOB(1073741823),
  PREVIEW     BLOB
);