CREATE TABLE ARCHITECTURE (
  ID          INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  NAME        VARCHAR(255)    NOT NULL,
  DESCRIPTION CLOB(1073741823),
  USECASE     CLOB(1073741823),
  PREVIEW     BLOB
)