CREATE TABLE MODULE (
  ID          INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  LAY_ID      INT             NOT NULL,
  NAME        VARCHAR(255)    NOT NULL,
  DESCRIPTION CLOB(1073741823)
)
