CREATE TABLE PATERNS (
  ID          INT PRIMARY KEY  NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  MOD_ID      INT              NOT NULL,
  NAME        VARCHAR(255)     NOT NULL,
  VALUE       CLOB(1073741823) NOT NULL,
  ARCH_ID     INT,
  TYPE        VARCHAR(255),
  DESCRIPTION CLOB(1073741823),
  PREVIEW     BLOB
)