CREATE TABLE ARCHITECTURE
(
  ID          INTEGER NOT NULL,
  NAME        TEXT    NOT NULL,
  DESCRIPTION TEXT,
  USECASE     TEXT,
  PREVIEW     TEXT
);
CREATE UNIQUE INDEX ARCHITECTURE_ID_uindex ON ARCHITECTURE (ID);
CREATE TABLE ARCH_DONE
(
  ID      INTEGER NOT NULL,
  TASK_ID INTEGER NOT NULL,
  ARCH_ID INTEGER NOT NULL
);
CREATE TABLE LAYER
(
  ID          INTEGER NOT NULL,
  ARCH_ID     INTEGER NOT NULL,
  NAME        TEXT    NOT NULL,
  DESCRIPTION TEXT,
  FOREIGN KEY (ARCH_ID) REFERENCES ARCHITECTURE (ID)
    DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX LAYER_ID_uindex ON LAYER (ID);
CREATE TABLE LAY_DONE
(
  ID           INTEGER NOT NULL,
  ARCH_DONE_ID INTEGER NOT NULL,
  LAY_ID       INTEGER NOT NULL
);
CREATE TABLE MODULE
(
  ID          INTEGER NOT NULL,
  LAY_ID      INTEGER NOT NULL,
  NAME        TEXT    NOT NULL,
  DESCRIPTION TEXT,
  FOREIGN KEY (LAY_ID) REFERENCES LAYER (ID)
    DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX MODULE_ID_uindex ON MODULE (ID);
CREATE TABLE MODULE_DONE
(
  ID          INTEGER NOT NULL,
  LAY_DONE_ID INTEGER NOT NULL,
  MOD_ID      INTEGER NOT NULL,
  PATTERN_ID  INTEGER NOT NULL,
  FOREIGN KEY (MOD_ID) REFERENCES MODULE (ID)
    DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE PATERNS
(
  ID          INTEGER NOT NULL,
  MOD_ID      INTEGER NOT NULL,
  NAME        TEXT    NOT NULL,
  VALUE       TEXT    NOT NULL,
  DESCRIPTION TEXT,
  PREVIEW     TEXT,
  ARCH_ID     INTEGER,
  TYPE        TEXT,
  FOREIGN KEY (MOD_ID) REFERENCES MODULE (ID)
    DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX PATERNS_ID_uindex ON PATERNS (ID);
CREATE TABLE TASK
(
  ID          INTEGER NOT NULL,
  NAME        TEXT    NOT NULL,
  DESCRIPTION TEXT    NOT NULL
);