CREATE TABLE SESSION (
  ID           INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  TASK_ID      INT             NOT NULL,
  CRITERION_ID INT             NOT NULL,
  DATE_SES     FLOAT           NOT NULL,
  NOTE CLOB(1073741823)
)