CREATE TABLE MARK (
  ID            INT PRIMARY KEY NOT NULL
  GENERATED ALWAYS AS IDENTITY
    ( START WITH 1, INCREMENT BY 1),
  SESSION_ID    INT NOT NULL,
  ARCH_1_ID     INT NOT NULL,
  ARCH_2_ID     INT NOT NULL,
  MARK          INT NOT NULL
)